### ISSUE TITLE
Error Running PyCript

### ISSUE THREAD

**Issue by Smont144** [Anof-cyber/PyCript#19]
Traceback (most recent call last):
  File "C:\PyCript\pycript.py", line 17, in <module>
    from pycript.encryption import Parameterencrypt
  File "C:\PyCript\pycript\encryption.py", line 1, in <module>
    from . import encoding, decoding
ImportError: cannot import name encoding

	at org.python.core.Py.ImportError(Py.java:327)
	at org.python.core.imp.importFromAs(imp.java:1648)
	at org.python.core.imp.importFrom(imp.java:1611)
	at pycript.encryption$py.f$0(C:/PyCript/pycript/encryption.py:7)
	at pycript.encryption$py.call_function(C:/PyCript/pycript/encryption.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:632)
	at org.python.core.imp.createFromPyClass(imp.java:314)
	at org.python.core.imp.createFromPyClass(imp.java:257)
	at org.python.core.imp.loadFromSource(imp.java:931)
	at org.python.core.imp.find_module(imp.java:771)
	at org.python.core.PyModule.findSubModule(PyModule.java:140)
	at org.python.core.PyModule.impAttr(PyModule.java:107)
	at org.python.core.imp.import_next(imp.java:1163)
	at org.python.core.imp.import_logic(imp.java:1280)
	at org.python.core.imp.import_module_level(imp.java:1371)
	at org.python.core.imp.importName(imp.java:1544)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1285)
	at org.python.core.PyObject.__call__(PyObject.java:433)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1636)
	at org.python.core.imp.importFrom(imp.java:1611)
	at org.python.pycode._pyx4.f$0(C:/PyCript/pycript.py:1625)
	at org.python.pycode._pyx4.call_function(C:/PyCript/pycript.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1742)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:535)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:287)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at burp.Zzku.ZW(Unknown Source)
	at burp.Zjcd.Zf(Unknown Source)
	at burp.Zio2.ZC(Unknown Source)
	at burp.Zr21.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by Smont144** [comment]
How do I solve this problem?

**Comment by Anof-cyber** [comment]
The problem is solved, you can download the updated version of the code with Git Clone or a Zip file
https://github.com/Anof-cyber/PyCript/archive/refs/heads/main.zip
